export const SIGN_UP_FAILURE = "SIGN_UP_FAILURE"
export const SIGN_UP_REQUEST = "SIGN_UP_REQUEST"
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS"
export const SIGN_UP_FAILURE_DELETE = "SIGN_UP_FAILURE_DELETE"

export const LOG_IN_FAILURE = "LOG_IN_FAILURE"
export const LOG_IN_REQUEST = "LOG_IN_REQUEST"
export const LOG_IN_SUCCESS = "LOG_IN_SUCCESS"
export const LOG_IN_FAILURE_DELETE = "LOG_IN_FAILURE_DELETE"

export const LOG_OUT_FAILURE = "LOG_OUT_FAILURE"
export const LOG_OUT_REQUEST = "LOG_OUT_REQUEST"
export const LOG_OUT_SUCCESS = "LOG_OUT_SUCCESS"

export const LOAD_MY_INFO_SUCCESS = "LOAD_MY_INFO_SUCCESS"
export const LOAD_MY_INFO_REQUEST = "LOAD_MY_INFO_REQUEST"
export const LOAD_MY_INFO_FAILURE = "LOAD_MY_INFO_FAILURE"

export const LOAD_USER_FAILURE = "LOAD_USER_FAILURE"
export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST"
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS"

export const USER_PROFILE_FAILURE = "USER_PROFILE_FAILURE"
export const USER_PROFILE_REQUEST = "USER_PROFILE_REQUEST"
export const USER_PROFILE_SUCCESS = "USER_PROFILE_SUCCESS"

export const USER_UPDATE_FAILURE = "USER_UPDATE_FAILURE"
export const USER_UPDATE_REQUEST = "USER_UPDATE_REQUEST"
export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS"

export const FORGOT_PASSWORD_FAILURE = "FORGOT_PASSWORD_FAILURE"
export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST"
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS"

export const RESET_PASSWORD_FAILURE = "RESET_PASSWORD_FAILURE"
export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST"
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS"



//CATEGORY 
export const CATEGORY_GET_REQUEST = "CATEGORY_GET_REQUEST";
export const CATEGORY_GET_SUCCESS = "CATEGORY_GET_SUCCESS";
export const CATEGORY_GET_FAILURE = "CATEGORY_GET_FAILURE";

export const CATEGORY_READ_REQUEST = "CATEGORY_READ_REQUEST";
export const CATEGORY_READ_SUCCESS = "CATEGORY_READ_SUCCESS";
export const CATEGORY_READ_FAILURE = "CATEGORY_READ_FAILURE";

export const CATEGORY_ADD_REQUEST = "CATEGORY_ADD_REQUEST";
export const CATEGORY_ADD_SUCCESS = "CATEGORY_ADD_SUCCESS";
export const CATEGORY_ADD_FAILURE = "CATEGORY_ADD_FAILURE";

export const CATEGORY_DELETE_REQUEST = "CATEGORY_DELETE_REQUEST";
export const CATEGORY_DELETE_SUCCESS = "CATEGORY_DELETE_SUCCESS";
export const CATEGORY_DELETE_FAILURE = "CATEGORY_DELETE_FAILURE";

export const CATEGORY_MOUSE_MOVE_REQUEST = "CATEGORY_MOUSE_MOVE_REQUEST";
export const CATEGORY_MOUSE_MOVE_SUCCESS = "CATEGORY_MOUSE_MOVE_SUCCESS";
export const CATEGORY_MOUSE_MOVE_FAILURE = "CATEGORY_MOUSE_MOVE_FAILURE";

export const CATEGORY_BLOGS_GET_REQUEST = "CATEGORY_BLOGS_GET_REQUEST";
export const CATEGORY_BLOGS_GET_SUCCESS = "CATEGORY_BLOGS_GET_SUCCESS";
export const CATEGORY_BLOGS_GET_FAILURE = "CATEGORY_BLOGS_GET_FAILURE";

//TAG 
export const TAG_GET_REQUEST = "TAG_GET_REQUEST";
export const TAG_GET_SUCCESS = "TAG_GET_SUCCESS";
export const TAG_GET_FAILURE = "TAG_GET_FAILURE";

export const TAG_READ_REQUEST = "TAG_READ_REQUEST";
export const TAG_READ_SUCCESS = "TAG_READ_SUCCESS";
export const TAG_READ_FAILURE = "TAG_READ_FAILURE";

export const TAG_ADD_REQUEST = "TAG_ADD_REQUEST";
export const TAG_ADD_SUCCESS = "TAG_ADD_SUCCESS";
export const TAG_ADD_FAILURE = "TAG_ADD_FAILURE";

export const TAG_DELETE_REQUEST = "TAG_DELETE_REQUEST";
export const TAG_DELETE_SUCCESS = "TAG_DELETE_SUCCESS";
export const TAG_DELETE_FAILURE = "TAG_DELETE_FAILURE";

export const TAG_MOUSE_MOVE_REQUEST = "TAG_MOUSE_MOVE_REQUEST";
export const TAG_MOUSE_MOVE_SUCCESS = "TAG_MOUSE_MOVE_SUCCESS";
export const TAG_MOUSE_MOVE_FAILURE = "TAG_MOUSE_MOVE_FAILURE";

export const TAGS_BLOGS_GET_REQUEST = "TAGS_BLOGS_GET_REQUEST";
export const TAGS_BLOGS_GET_SUCCESS = "TAGS_BLOGS_GET_SUCCESS";
export const TAGS_BLOGS_GET_FAILURE = "TAGS_BLOGS_GET_FAILURE";



//BLOG
export const BLOG_GET_REQUEST = "BLOG_GET_REQUEST";
export const BLOG_GET_SUCCESS = "BLOG_GET_SUCCESS";
export const BLOG_GET_FAILURE = "BLOG_GET_FAILURE";

export const BLOG_RELATED_REQUEST = "BLOG_RELATED_REQUEST";
export const BLOG_RELATED_SUCCESS = "BLOG_RELATED_SUCCESS";
export const BLOG_RELATED_FAILURE = "BLOG_RELATED_FAILURE";


export const BLOG_READ_REQUEST = "BLOG_READ_REQUEST";
export const BLOG_READ_SUCCESS = "BLOG_READ_SUCCESS";
export const BLOG_READ_FAILURE = "BLOG_READ_FAILURE";

export const BLOG_ADD_REQUEST = "BLOG_ADD_REQUEST";
export const BLOG_ADD_SUCCESS = "BLOG_ADD_SUCCESS";
export const BLOG_ADD_FAILURE = "BLOG_ADD_FAILURE";

export const BLOG_DELETE_REQUEST = "BLOG_DELETE_REQUEST";
export const BLOG_DELETE_SUCCESS = "BLOG_DELETE_SUCCESS";
export const BLOG_DELETE_FAILURE = "BLOG_DELETE_FAILURE";

export const BLOG_UPDATE_REQUEST = "BLOG_UPDATE_REQUEST";
export const BLOG_UPDATE_SUCCESS = "BLOG_UPDATE_SUCCESS";
export const BLOG_UPDATE_FAILURE = "BLOG_UPDATE_FAILURE";


export const BLOG_MOUSE_MOVE_REQUEST = "BLOG_MOUSE_MOVE_REQUEST";
export const BLOG_MOUSE_MOVE_SUCCESS = "BLOG_MOUSE_MOVE_SUCCESS";
export const BLOG_MOUSE_MOVE_FAILURE = "BLOG_MOUSE_MOVE_FAILURE";

export const BLOG_SEARCH_REQUEST = "BLOG_SEARCH_REQUEST";
export const BLOG_SEARCH_SUCCESS = "BLOG_SEARCH_SUCCESS";
export const BLOG_SEARCH_FAILURE = "BLOG_SEARCH_FAILURE";


//form
export const FORM_MEESAGE_GET = "FORM_MEESAGE_GET"
export const FORM_MEESAGE_SUCCESS = "FORM_MEESAGE_SUCCESS"
export const FORM_MEESAGE_FAILURE = "FORM_MEESAGE_FAILURE"

export const FORM_AUTHOR_MEESAGE_GET = "FORM_AUTHOR_MEESAGE_GET"
export const FORM_AUTHOR_MEESAGE_SUCCESS = "FORM_AUTHOR_MEESAGE_SUCCESS"
export const FORM_AUTHOR_MEESAGE_FAILURE = "FORM_AUTHOR_MEESAGE_FAILURE"